minor fixes in script/screencapture; - set suspend as default mode for script/screencapture, add usage

diff --git a/script/screenlock b/script/screenlock
--- a/script/screenlock
+++ b/script/screenlock
@@ -7,15 +7,36 @@ HIBERNATE_CMD="loginctl hibernate"
 SUSPEND_CMD="loginctl suspend-then-hibernate"
 SCREENLOCK_CMD=slock
 IMMEDIATE_MODE=0
-SUSPEND_MODE=0
+MODE=""
 XIDLEHOOK_PID=
 
+usage() {
+  cat <<EOF
+Usage: screenlock [options]
+Options:
+-s --suspend    Suspend system to memory (default).
+-b --hibernate  Suspend system to disc.
+-i --immediate  Suspen immediately.
+-h --help       Show this help message.
+EOF
+}
+
 start_idlehook() {
-    [ -x "$(command -v xidlehook)" ] || return 0
-    [ "$SUSPEND_MODE" -eq 1 ] && SLEEP_CMD="$SUSPEND_CMD" || SLEEP_CMD="$HIBERNATE_CMD"
+    if [ ! -x "$(command -v xidlehook)" ]; then
+      echo "\"xidlehook\" executable not found."
+      exit 1
+    fi
+    case "$MODE" in
+      s) SLEEP_CMD="$SUSPEND_CMD" ;;
+      h) SLEEP_CMD="$HIBERNATE_CMD" ;;
+    esac
     xidlehook --detect-sleep --timer "$HIBERNATE_TIMEOUT" "$SLEEP_CMD" "" &
     XIDLEHOOK_PID=$!
-    [ "$IMMEDIATE_MODE" -eq 1 ] && (sleep "$IMMEDIATE_TIMEOUT" && $SLEEP_CMD) &  # give some time to actually lock
+    if [ "$IMMEDIATE_MODE" -eq 1 ]; then
+      # give some time to actually lock
+      sleep "$IMMEDIATE_TIMEOUT"
+      $SLEEP_CMD &
+    fi
 }
 
 stop_idlehook() {
@@ -37,10 +58,27 @@ restore_kb_layout() {
 while [ $# -gt 0 ]; do
     case $1 in
         -i|--immediate) IMMEDIATE_MODE=1 ;;
-        -s|--suspend) SUSPEND_MODE=1 ;;
+        -s|--suspend)
+          if [ -n "$MODE" ]; then
+            echo "Multiple options selected: -i, -s"
+            exit 1
+          fi
+          MODE="s"
+          ;;
+        -b|--hibernate)
+          if [ -n "$MODE" ]; then
+            echo "Multiple options selected: -i, -s"
+            exit 1
+          fi
+          MODE="h"
+          ;;
+        -h|--help) usage ; exit 0 ;;
     esac
     shift
 done
+if [ -z "$MODE" ]; then
+  MODE="s"
+fi
 
 if [ -x "$(command -v $SCREENLOCK_CMD)" ]; then
   start_idlehook
